### ISSUE TITLE
Добавить в index2.html четвертый комментарий.

### ISSUE THREAD

**Issue by TrofimchikEwgeni** [TrofimchikEwgeni/index2.html#1]
Задачу выполнить в отдельной ветке, а после выполнения — создать pull request и перевести задачу обратно на меня.

**Comment by EwgenTrafimchyk** [comment]
Задача выполнена в  отдельной ветке 1-new-comment-index2.  Pull request создан, задача переведена обратно на Вас.

**Comment by TrofimchikEwgeni** [comment]
Задача выполнена хорошо. Все ок.
